#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/../schema/database

# psql -f global-drop.sql $@
psql -f global.sql $@
psql -f lang.sql $@
psql -f ingredient.sql $@
psql -f persons.sql $@
psql -f recipe.sql $@
psql -f recipe_comments.sql $@
psql -f recipe_ingredients.sql $@
psql -f recipe_steps.sql $@
psql -f security.sql $@
psql -f test/data.sql $@